// Nalam — Reports Screen
import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Share } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import Colors from '../theme/colors';
import { Spacing, Radius, Shadow } from '../theme/spacing';
import { FontSize, FontWeight } from '../theme/typography';
import useProgressStore from '../store/progressStore';
import useUserStore from '../store/userStore';
import DateUtils from '../utils/dateUtils';

const PERIODS = [
  { key: 'weekly', label: 'Weekly', icon: '📅' },
  { key: 'monthly', label: 'Monthly', icon: '📆' },
  { key: 'quarterly', label: 'Quarterly', icon: '📊' },
];

const ReportsScreen = () => {
  const [period, setPeriod] = useState('weekly');
  const [stats, setStats] = useState({ calories: [], workouts: [], meditations: [] });
  const { getWeeklyReport, getMonthlyReport, getQuarterlyReport } = useProgressStore();
  const profile = useUserStore(s => s.profile);

  const loadReport = async (p) => {
    let data;
    if (p === 'weekly') data = await getWeeklyReport();
    else if (p === 'monthly') data = await getMonthlyReport();
    else data = await getQuarterlyReport();
    setStats(data || { calories: [], workouts: [], meditations: [] });
  };

  useEffect(() => { loadReport(period); }, [period]);

  const totalWorkouts = stats.workouts?.length || 0;
  const totalMeditations = stats.meditations?.length || 0;
  const avgCalories = stats.calories?.length
    ? Math.round(stats.calories.reduce((s, c) => s + (c.total || 0), 0) / stats.calories.length)
    : 0;
  const totalMedMins = stats.meditations?.reduce((s, m) => s + (m.duration_minutes || 0), 0) || 0;

  const periodLabel = {
    weekly: 'This Week',
    monthly: 'This Month',
    quarterly: 'Last 90 Days',
  }[period];

  const handleShare = async () => {
    const msg = `🌺 Nalam Report — ${periodLabel}

👤 ${profile?.name || 'User'} | Starting: ${profile?.startWeight}kg | Current: ${profile?.currentWeight}kg
📉 Lost: ${(profile?.startWeight - profile?.currentWeight).toFixed(1)}kg

💪 Workouts completed: ${totalWorkouts}
🧘 Meditation sessions: ${totalMeditations} (${totalMedMins} min)
🍛 Avg daily calories: ${avgCalories} kcal

Generated by Nalam — Your Wellness, Your Roots 🙏`;
    await Share.share({ message: msg });
  };

  const summaryItems = [
    { icon: '💪', label: 'Workouts Completed', value: `${totalWorkouts}`, color: Colors.secondary },
    { icon: '🍛', label: 'Avg Daily Calories', value: avgCalories ? `${avgCalories} kcal` : 'No data', color: Colors.primary },
    { icon: '🧘', label: 'Meditation Sessions', value: `${totalMeditations}`, color: Colors.maroon },
    { icon: '⏱️', label: 'Total Meditation Time', value: `${totalMedMins} min`, color: Colors.accent },
    { icon: '🏆', label: 'Workout Rate', value: totalWorkouts > 0 ? `${Math.round((totalWorkouts / (period === 'weekly' ? 5 : period === 'monthly' ? 20 : 65)) * 100)}%` : '0%', color: Colors.accentLight },
  ];

  const weightLost = profile ? (profile.startWeight - profile.currentWeight).toFixed(1) : 0;
  // BUG-004 fix: guard division by zero when startWeight === targetWeight
  const goalPct = profile
    ? (profile.startWeight === profile.targetWeight
      ? 0
      : Math.min(100, Math.max(0, Math.round(
          ((profile.startWeight - profile.currentWeight) / (profile.startWeight - profile.targetWeight)) * 100
        ))))
    : 0;

  return (
    <ScrollView style={styles.screen}>
      <LinearGradient colors={[Colors.accent, Colors.accentLight]} style={styles.header}>
        <Text style={styles.headerTitle}>📊 Reports</Text>
        <Text style={styles.headerSub}>Track your transformation journey</Text>
      </LinearGradient>

      <View style={styles.content}>
        {/* Period selector */}
        <View style={styles.periodRow}>
          {PERIODS.map(p => (
            <TouchableOpacity key={p.key} onPress={() => setPeriod(p.key)}
              style={[styles.periodBtn, period === p.key && styles.periodBtnActive]}>
              <Text style={styles.periodIcon}>{p.icon}</Text>
              <Text style={[styles.periodLabel, period === p.key && styles.periodLabelActive]}>
                {p.label}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Overall goal progress */}
        <View style={styles.goalCard}>
          <View style={styles.goalHeader}>
            <Text style={styles.goalTitle}>Overall Goal Progress</Text>
            <Text style={styles.goalPct}>{Math.max(0, goalPct)}%</Text>
          </View>
          <View style={styles.goalBarBg}>
            <View style={[styles.goalBarFill, { width: `${Math.min(100, Math.max(0, goalPct))}%` }]} />
          </View>
          <View style={styles.goalDetails}>
            <Text style={styles.goalDetail}>📉 Lost: <Text style={styles.bold}>{weightLost} kg</Text></Text>
            <Text style={styles.goalDetail}>🎯 Target: <Text style={styles.bold}>{profile?.targetWeight} kg</Text></Text>
          </View>
        </View>

        {/* Period summary */}
        <Text style={styles.sectionTitle}>{periodLabel} Summary</Text>
        {summaryItems.map((item, i) => (
          <View key={i} style={styles.summaryRow}>
            <View style={[styles.summaryIcon, { backgroundColor: item.color + '20' }]}>
              <Text style={styles.summaryIconEmoji}>{item.icon}</Text>
            </View>
            <Text style={styles.summaryLabel}>{item.label}</Text>
            <Text style={[styles.summaryValue, { color: item.color }]}>{item.value}</Text>
          </View>
        ))}

        {/* Workout log list */}
        {stats.workouts && stats.workouts.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>💪 Workout Log</Text>
            <View style={styles.logCard}>
              {stats.workouts.map((w, i) => (
                <View key={i} style={styles.logRow}>
                  <Text style={styles.logDate}>{DateUtils.formatDate(w.date)}</Text>
                  <Text style={styles.logFocus}>{w.focus}</Text>
                  <Text style={styles.logCal}>~{w.calories_burned} kcal</Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Meditation log */}
        {stats.meditations && stats.meditations.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>🧘 Meditation Log</Text>
            <View style={styles.logCard}>
              {stats.meditations.map((m, i) => (
                <View key={i} style={styles.logRow}>
                  <Text style={styles.logDate}>{DateUtils.formatDate(m.date)}</Text>
                  <Text style={styles.logFocus}>{m.session_name}</Text>
                  <Text style={styles.logCal}>{m.duration_minutes} min</Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Empty state */}
        {totalWorkouts === 0 && totalMeditations === 0 && avgCalories === 0 && (
          <View style={styles.emptyState}>
            <Text style={styles.emptyEmoji}>🌱</Text>
            <Text style={styles.emptyTitle}>Your journey is just beginning!</Text>
            <Text style={styles.emptySub}>Start logging meals, workouts and meditations. Your first report will appear here.</Text>
          </View>
        )}

        {/* Share button */}
        <TouchableOpacity onPress={handleShare}>
          <LinearGradient colors={Colors.gradientAccent} style={styles.shareBtn}>
            <Text style={styles.shareBtnText}>📤 Share My Report</Text>
          </LinearGradient>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background },
  header: { paddingTop: 56, paddingHorizontal: Spacing.base, paddingBottom: Spacing.xl },
  headerTitle: { fontSize: FontSize.xl, fontWeight: FontWeight.bold, color: Colors.white, marginBottom: 4 },
  headerSub: { fontSize: FontSize.sm, color: Colors.white + 'CC' },
  content: { padding: Spacing.base },
  periodRow: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.base },
  periodBtn: { flex: 1, alignItems: 'center', padding: Spacing.sm, borderRadius: Radius.xl, backgroundColor: Colors.surface, borderWidth: 1.5, borderColor: Colors.sandalwood, ...Shadow.sm },
  periodBtnActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  periodIcon: { fontSize: 22, marginBottom: 2 },
  periodLabel: { fontSize: FontSize.xs, fontWeight: FontWeight.semiBold, color: Colors.textMuted },
  periodLabelActive: { color: Colors.white },
  goalCard: { backgroundColor: Colors.surface, borderRadius: Radius.xl, padding: Spacing.base, ...Shadow.sm, marginBottom: Spacing.base },
  goalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.sm },
  goalTitle: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: Colors.textPrimary },
  goalPct: { fontSize: FontSize.xl, fontWeight: FontWeight.extraBold, color: Colors.accent },
  goalBarBg: { height: 10, backgroundColor: Colors.sandalwood, borderRadius: Radius.full, overflow: 'hidden', marginBottom: Spacing.sm },
  goalBarFill: { height: '100%', backgroundColor: Colors.accent, borderRadius: Radius.full },
  goalDetails: { flexDirection: 'row', justifyContent: 'space-between' },
  goalDetail: { fontSize: FontSize.sm, color: Colors.textMuted },
  bold: { fontWeight: FontWeight.bold, color: Colors.textPrimary },
  sectionTitle: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: Colors.textPrimary, marginBottom: Spacing.sm, marginTop: Spacing.sm },
  summaryRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.surface, borderRadius: Radius.lg, padding: Spacing.md, marginBottom: Spacing.sm, ...Shadow.sm, gap: Spacing.sm },
  summaryIcon: { width: 40, height: 40, borderRadius: Radius.full, alignItems: 'center', justifyContent: 'center' },
  summaryIconEmoji: { fontSize: 20 },
  summaryLabel: { flex: 1, fontSize: FontSize.sm, color: Colors.textSecondary },
  summaryValue: { fontSize: FontSize.md, fontWeight: FontWeight.bold },
  logCard: { backgroundColor: Colors.surface, borderRadius: Radius.xl, padding: Spacing.base, ...Shadow.sm, marginBottom: Spacing.md },
  logRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: Colors.sandalwood + '50', gap: Spacing.sm },
  logDate: { fontSize: FontSize.xs, color: Colors.textMuted, width: 45 },
  logFocus: { flex: 1, fontSize: FontSize.sm, color: Colors.textPrimary },
  logCal: { fontSize: FontSize.xs, color: Colors.primary, fontWeight: FontWeight.semiBold },
  emptyState: { alignItems: 'center', padding: Spacing.xl },
  emptyEmoji: { fontSize: 56, marginBottom: Spacing.md },
  emptyTitle: { fontSize: FontSize.lg, fontWeight: FontWeight.bold, color: Colors.textPrimary, marginBottom: Spacing.sm },
  emptySub: { fontSize: FontSize.sm, color: Colors.textMuted, textAlign: 'center', lineHeight: 22 },
  shareBtn: { borderRadius: Radius.full, padding: Spacing.base, alignItems: 'center', marginTop: Spacing.md, marginBottom: Spacing.xl },
  shareBtnText: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: Colors.white },
});

export default ReportsScreen;
